enable logging with otel-collector

diff --git a/release/kubernetes-manifests.yaml b/release/kubernetes-manifests.yaml
--- a/release/kubernetes-manifests.yaml
+++ b/release/kubernetes-manifests.yaml
@@ -499,25 +499,25 @@ spec:
       serviceAccountName: default
       terminationGracePeriodSeconds: 5
       restartPolicy: Always
-      initContainers:
-      - command:
-        - /bin/sh
-        - -exc
-        - |
-          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
-          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
-          if test $STATUSCODE -ne 200; then
-              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-              exit 1
-          fi
-        name: frontend-check
-        image: busybox:latest
-        env:
-        - name: FRONTEND_ADDR
-          value: "frontend:80"
+      # initContainers:
+      # - command:
+      #   - /bin/sh
+      #   - -exc
+      #   - |
+      #     echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+      #     STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+      #     if test $STATUSCODE -ne 200; then
+      #         echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+      #         exit 1
+      #     fi
+      #   name: frontend-check
+      #   image: busybox:latest
+      #   env:
+      #   - name: FRONTEND_ADDR
+      #     value: "frontend:80"
       containers:
       - name: main
-        image: k6-grpc:local
+        image: k6-loadgenerator:local
         env:
         - name: FRONTEND_ADDR
           value: "frontend:80"
@@ -668,6 +668,7 @@ spec:
       containers:
       - name: redis
         image: redis:alpine
+        command: ["redis-server", "--appendonly", "yes"]
         ports:
         - containerPort: 6379
         readinessProbe:
